### PR TITLE
Contact us page

### PR DESCRIPTION
**Pull request by mustachemo**
Contact page is done. 

- There is a tab in the Navbar called "contact us" that will take you to the /contactus page
- Once you write your name, email, and message; they will go FIREBASE (a google cloud service) to be stored in a database called "Cloud Firestore"
- The documents/messages will be stored by the "full name" field with a timestamp attached to them to make them unique
- There is no way to get back home, so someone needs to make a navbar tab to go back home to "/" route
- The Firestore is made with my google account, but can be moved if needed. I can also added authenticated users to check the documents
- Later on we can display the messages/documents in a nice manner to see all the messages we have gotten

This is a snapshot of what the firestore looks like with my message in it:
Screenshot 2023-12-29 at 11 40 38 PM

This is how the contact us page looks:
Screenshot 2023-12-29 at 11 43 24 PM

### CODE REVIEW

**Comment by AlissonRoss** [comment]
Great work on this Mo. Awesome PR. I am going to approve this soon and work on the responsiveness of it. 
image
Just needs some responsiveness fixes along with fixing the links on the navbar.
Clicking on the FAQ, Tracks, Sponsors and Team on the navbar from the Contact Us page doesnt redirect to the homepage. I will fix this at some point along with the responsiveness. 
Thank you once again!

**Comment by mustachemo** [comment]
Sounds great!

**Comment by AlissonRoss** [comment]
Just realized: You will need to create a .env and purge this, then open a new PR without the .env. Check out the Backend text channel for more details.

**Comment by AlissonRoss** [comment]
Oh! Generate a new key, put it inside the .env and you should be ok.

**Comment by mustachemo** [comment]
generated a new key and shared it with you Alisson! I deleted the old api key, it is unusable

That was very nooby of me.

**Comment by AlissonRoss** [comment]
Did you update firebase.js with props? It should take in the .env file and take the props from the env. Please keep me posted when you make the change

**Pull request merged**
